services:
  postgres:
    image: postgres:16-alpine
    container_name: token-tracker-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: tokentracker
      POSTGRES_PASSWORD: tokentracker
      POSTGRES_DB: tokentracker
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  # To re-run later if you add new changesets, just run: docker compose up liquibase
  liquibase:
    build: ./liquibase
    volumes:
      - ./liquibase/changelog:/liquibase/changelog
    command: >
      --url=jdbc:postgresql://postgres:5432/tokentracker
      --username=tokentracker
      --password=tokentracker
      --searchPath=/liquibase/changelog
      --changeLogFile=db.changelog-master.yaml
      update
    depends_on:
      postgres:
        condition: service_started
